apiVersion: apps/v1
kind: Deployment
metadata:
  name:  go-app
  namespace: default
  labels:
    app:  go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  go-app
    spec:
      containers:
      - name:  go-app
        image: carlosgenuino/gointensivo-jul:latest
        ports:
          - containerPort: 8080