apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: default
spec:
  selector:
    app: go-app
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: go-app
    protocol: TCP
    port: 8080
    targetPort: 8080